name: docs

on:
  push:
  workflow_dispatch:

jobs:
  docs:
    if: "!contains(github.event.head_commit.message, '[skip ci]')" 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build docs
        uses: TinyTapeout/tt-gds-action/docs@tt09
